$image = /home/snow/Pictures/Wallpapers/327.webp
$surface_alpha = rgba(30,16,124d)
$background = rgba(30,16,12,ff)
$error = rgba(255,180,171,ff)
$error_container = rgba(147,0,10,ff)
$on_background = rgba(249,220,213,ff)
$on_error = rgba(105,0,5,ff)
$on_error_container = rgba(255,218,214,ff)
$on_primary = rgba(94,23,0,ff)
$on_primary_container = rgba(255,219,208,ff)
$on_secondary = rgba(73,40,15,ff)
$on_secondary_container = rgba(255,220,198,ff)
$on_surface = rgba(249,220,213,ff)
$on_surface_variant = rgba(220,193,185,ff)
$on_tertiary = rgba(71,42,0,ff)
$on_tertiary_container = rgba(255,221,184,ff)
$outline = rgba(163,139,133,ff)
$outline_variant = rgba(85,66,61,ff)
$primary = rgba(255,181,158,ff)
$primary_container = rgba(133,36,0,ff)
$secondary = rgba(241,187,152,ff)
$secondary_container = rgba(99,62,35,ff)
$shadow = rgba(0,0,0,ff)
$surface = rgba(30,16,12,ff)
$surface_bright = rgba(43,28,23,ff)
$surface_container = rgba(43,28,23,ff)
$surface_container_high = rgba(85,66,61,ff)
$surface_dim = rgba(30,16,12,ff)
$surface_variant = rgba(85,66,61,ff)
$tertiary = rgba(243,189,123,ff)
$tertiary_container = rgba(100,63,7,ff)
$text_color = $on_surface
$entry_background_color = $surface_alpha
$entry_border_color = $tertiary
$entry_color = $on_surface
