[config]
reload_apps = true
source_color_index = 0 

[templates.hyprland]
input_path = '/home/snow/Dotfiles/matugen/.config/matugen/templates/hyprland-colors.conf'
output_path = '/home/snow/.cache/skwd-wall/hyprland-colors.conf'

[templates.kitty]
input_path = '/home/snow/Dotfiles/matugen/.config/matugen/templates/kitty-colors.conf'
output_path = '/home/snow/.cache/skwd-wall/colors-kitty.conf'

[templates.fuzzel]
input_path = '/home/snow/Dotfiles/matugen/.config/matugen/templates/fuzzel-colors.ini'
output_path = '/home/snow/.cache/skwd-wall/fuzzel-colors.ini'

[post_processing]
command = "/home/snow/.local/bin/wall-sync.sh %path%"
run_on_change = true
