########################################################################
##  SnowDots — SnowColorsmatugen                             Version: v1.0.0    ##
##  Last Edited: 2026-04-29                                           ##
########################################################################

cursor #89d0ed
cursor_text_color #003544

active_tab_foreground   #dee3e6
active_tab_background   #303638
inactive_tab_foreground #c0c8cc
inactive_tab_background #0a0f11

foreground            #dee3e6
background            #0f1417
selection_foreground  #cfe6f1
selection_background  #354a53

color0  #303638
color8  #8a9296

color1  #ffb4ab
color9  #93000a

color2  #89d0ed
color10 #004d62

color3  #c4c3eb
color11 #444465

color4  #b3cad5
color12 #354a53

color5  #89d0ed
color13 #004d62

color6  #b3cad5
color14 #354a53

color7  #dee3e6
color15 #c0c8cc
