$color1 = rgba({{colors.primary_fixed.default.hex_stripped}}ff)
$color4 = rgba({{colors.primary_fixed_dim.default.hex_stripped}}ff)
$inactive = rgba({{colors.surface_container_lowest.default.hex_stripped}}aa)
