########################################################################
##  SnowDots — fuzzelcolors                             Version: v1.0.0    ##
##  Last Edited: 2026-04-30                                           ##
########################################################################

[main]
font=JetBrainsMono Nerd Font:size=12
prompt="󰣇  "
icon-theme=Papirus-Dark
show-icons=yes
width=35
lines=12
inner-pad=10

[colors]
background={{colors.surface.default.hex_stripped}}dd
text={{colors.on_surface.default.hex_stripped}}ff
match={{colors.primary.default.hex_stripped}}ff
selection={{colors.primary_fixed_dim.default.hex_stripped}}ff
selection-text={{colors.on_primary_container.default.hex_stripped}}ff
border={{colors.primary.default.hex_stripped}}ff

[border]
width=2
radius=10
