########################################################################

##  Last Edited: 2026-05-10                                           ##
########################################################################

########################################################################
##  SnowDots - Hyprland Matugen Colors                             Version: v1.0.0    ##
##  Last Edited: 2026-04-29                                           ##
########################################################################

$color1 = rgba({{colors.primary_fixed.default.hex_stripped}}ff)
$color4 = rgba({{colors.primary_fixed_dim.default.hex_stripped}}ff)
$inactive = rgba({{colors.surface_container_lowest.default.hex_stripped}}aa)

